name: test


on:
  issue_comment:
    types: [created]

jobs:
  print_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Print a static message
        run: echo "Hello world $COMMENT_BODY"
        env:
          COMMENT_BODY: ${{ github.event.issue.comments }}
        
      

    
      
  
